# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

defaults:
  run:
    working-directory: react

# Event for the workflow
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize]

# List of jobs
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      react: ${{ steps.filter.outputs.react }}
      tokengen: ${{ steps.filter.outputs.tokengen }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            react:
              - react/**
            tokengen:
              - token-gen/**
  chromatic-deployment:
    needs: [changes]
    if: ${{ needs.changes.outputs.react == 'true' }}
    # Operating System
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for v2
      - name: Install dependencies
        run: npm i
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: react
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitOnceUploaded: true
          autoAcceptChanges: main
          # Skip running Chromatic on dependabot PRs
          skip: dependabot/**
          # Ignore storybook colorTheme changes
          untraced: "react/.storybook/colorThemes/**"
