# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

defaults:
  run:
    working-directory: react

# Event for the workflow
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize]

# List of jobs
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      camp: ${{ steps.filter.outputs.camp }}
      tokengen: ${{ steps.filter.outputs.tokengen }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            camp:
              - packages/camp/**
            tokengen:
              - tooling/camp/token-gen/**
  chromatic-deployment:
    needs: [changes]
    if: ${{ needs.changes.outputs.camp == 'true' }}
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for v4
      - name: Install dependencies
        run: npm i
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: packages/camp
          storybookBaseDir: packages/camp
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitOnceUploaded: true
          autoAcceptChanges: main
          # Skip running Chromatic on dependabot PRs
          skip: dependabot/**
          # Ignore storybook colorTheme changes
          untraced: "packages/camp/.storybook/colorThemes/**"
